name: CI Workflow

on: ['push', 'pull_request']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.12'
      
      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies with Poetry
        run: poetry install --no-root

      - name: Run Pytest
        run: poetry run pytest -v
